# Generated by Django 3.1.7 on 2021-03-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-timestamp',)},
        ),
    ]
