# Generated by Django 3.1.7 on 2021-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210313_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
