# Generated by Django 3.1.7 on 2021-03-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Mining', 'Web'), ('Agriculture', 'Mobile'), ('Infrastructure', 'Desktop'), ('Power', 'Upcoming')], default='Mining', max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('image_one', models.URLField()),
                ('image_two', models.URLField(blank=True)),
                ('image_three', models.URLField(blank=True)),
                ('image_four', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
            ],
        ),
    ]
