# Generated by Django 3.1.7 on 2021-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Mining', 'Mining'), ('Agriculture', 'Agriculture'), ('Infrastructure', 'Infrastructure'), ('Power', 'Power')], default='Mining', max_length=20),
        ),
    ]
