# Generated by Django 3.1.7 on 2021-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210312_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('testimonial', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
